Feat home login route
Daily-Drip-Dev/Driply pull request #17
Opened 2024-12-31 03:10 UTC by lurgi

#16 

- "/" 라우트를 구현하며 홈 화면의 기본 레이아웃과 스타일링을 추가했습니다.
- 사용자 경험 개선을 위해 메타 태그와 배경색, 이미지 에셋 등을 설정했습니다.

### 주요 변경 사항
1. **홈 화면 라우트 구현**
   - `HomeLayout` 컴포넌트를 추가하여 홈 화면을 구성했습니다.
   - 카카오 간편 로그인 버튼 및 로고를 포함한 UI를 작성했습니다.

2. **메타 태그 등록**
   - `description` 및 `keywords` 태그 추가
     - **description**: Driply 서비스 소개.
     - **keywords**: 서비스 관련 키워드.

3. **이미지 에셋 추가**
   - 로고, 파비콘, 카카오 로고 등 기본 이미지 에셋 추가.

4. **스타일링**
   - 배경색 변경 (`#fff` → `#f7f6f4`).
   - `vanilla-extract`를 사용한 홈 화면 스타일 작성 (`styles.css.ts`).

### 변경 파일
- **`app/routes/_index.tsx`**: 
  - `meta` 함수 작성 및 `HomeLayout` 사용.
- **`app/layout/HomeLayout/index.tsx`**:
  - 홈 화면 구현.
- **`app/layout/HomeLayout/styles.css.ts`**:
- **`app/index.css`**:
  - 배경색 변경.

### 기타
- 카카오 간편 로그인 버튼 클릭 시 임시 경고창 표시(`alert`).
- 이전에 구현된 `Button` 공통 컴포넌트를 사용하여 카카오 로그인 버튼을 구현하려 하였으나,  스타일은 `className`으로 오버라이딩 되지 않습니다. 이는 정적 스타일링 툴의 특성으로 보입니다. 
  - style을 적용하는 것이 아닌, 만들어진 스타일 `className`을 적용하는 것이기 때문에, 오버라이딩 되지 않습니다.
  - 따라서 `Button` 공통 컴포넌트의 코드 수정이 필요해 보입니다.
---

리뷰 부탁드립니다!

2024-12-31 06:11 UTC, llqqssttyy requested changes
favicon까지 들어가니까 진짜 멋있네요~

<img width="210" alt="image" src="https://github.com/user-attachments/assets/6a749a28-7c3b-440d-9467-09afb3571498" />

간단한 변경사항 리뷰 남겼으니 확인해주세요~

나중에 지표 측정을 위해 남겨두는 기록
- 리뷰 요청부터 PR 확인까지 걸린 시간: 3시간
- PR 리뷰 시간: 20분

2024-12-31 06:11 UTC, llqqssttyy commented on app/layout/HomeLayout/styles.css.ts
> +  position: "relative",
요 속성은 왜 들어가게 됐나요?

2024-12-31 06:11 UTC, llqqssttyy commented on app/layout/HomeLayout/index.tsx
> +          <div className={styles.kakaoText}>카카오 간편 로그인</div>
[카카오 디자인 가이드](https://developers.kakao.com/docs/latest/ko/kakaologin/design-guide#kakaologin-button-guide-label)에 따르면 문구는 "카카오 로그인"으로 권장하네요~

2024-12-31 06:11 UTC, llqqssttyy commented on app/layout/HomeLayout/styles.css.ts
> +});
반응형을 고려해서 줄바꿈 방지 속성을 추가하면 좋겠습니다!
```
white-space: "nowrap",
```

2024-12-31 06:11 UTC, llqqssttyy commented on app/layout/HomeLayout/index.tsx
> +    // TODO: 카카오 로그인 연결
요 부분은 PR 머지 후 제 작업 브랜치에서 마저 작업할게요!

2024-12-31 06:11 UTC, llqqssttyy commented on app/routes/_index.tsx
> +    },
일잘러👍

2024-12-31 08:40 UTC, lurgi commented on app/layout/HomeLayout/styles.css.ts
> +  position: "relative",
ㅋㅋㅋㅋ 그러게요

2024-12-31 08:45 UTC, lurgi commented on app/layout/HomeLayout/index.tsx
> +          <div className={styles.kakaoText}>카카오 간편 로그인</div>
간편이란 단어가 사용되는게, 사용자에게 "빠르고 쉽게 로그인할 수 있겠구나"라는 긍정적인 인상을 만들어줄 수 있을 것 같다 생각했어요!

2024-12-31 08:49 UTC, lurgi commented on app/layout/HomeLayout/styles.css.ts
> +});
속성을 추가하는 것 괜찮아 보입니다!
+ 해당 텍스트는 244px에서 깨지기 시작하는데, 반응형을 어디까지 고려하면 좋을지 고민되네요~

2024-12-31 08:50 UTC, lurgi commented on app/routes/_index.tsx
> +    },
꼼곰하게 봐주셔서 감사함댱~

2025-01-05 06:27 UTC, llqqssttyy approved these changes
- approve까지 5days

2025-01-05 11:40 UTC, lurgi commented
> * approve까지 5days

5days는 너무한거 아니오?

2025-01-05 11:40 UTC, merged