feat: LogPreview 컴포넌트 구현 및 stitches, storybook 세팅
Daily-Drip-Dev/Driply pull request #7
Opened 2024-12-04 11:07 UTC by lurgi

LogPreview를 만드는 이슈로 시작하였으나, 간단하고 기본적인 세팅은 같이 진행하였습니다.

## 1. globalCss를 이용하여 font token을 만들었습니다.
heading에 대한 스타일은 오버라이딩 하였고, 다른 스타일은 calssName에 넣으면 적용됩니다.

## 2. preview-head.html을 이용한 storybook 세팅
스토리북에선 공통 스타일이 적용되지 않았고, 이를 적용하기 위해 preview-head.html에서 link 속성을 이용해 가져왔습니다.

## 3. Image 컴포넌트 구현
기존 Image컴포넌트에 isLoading과 isError를 넣은 간단한 공통 컴포넌트를 구현해봤습니다.
### state를 이용한 Stitches의 동적 스타일링 사용법
```
const Image = styled("img", {
  width: "100%",
  height: "100%",
  objectFit: "cover",

  variants: {
    isLoading: {
      true: {
        background: "linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%)",
        backgroundSize: "200% 100%",
        animation: `${skeletonAnimation} 1.5s infinite`,
        opacity: 0.5,
      },
      false: {
        background: "none",
        opacity: 1,
      },
    },
  },
});
```
variants를 사용하여 구현할 수 있습니다.

2024-12-05 13:04 UTC, llqqssttyy requested changes
(시험 준비로 확인이 늦어 죄송합니다.😅)

역시 굳굳👍
Image 컴포넌트와 LogPreview 컴포넌트 props에 대해서 간단한 코멘트 달았어요. 
생각해보신 후 리뷰요청 주세요~

2024-12-05 13:04 UTC, llqqssttyy commented on app/component/Image/style.ts
> +  },
스티치에서 동적 스타일링을 구현하는 방법이 신기하네요.🫢

2024-12-05 13:04 UTC, llqqssttyy commented on src/stitches.ts
> +});
굳굳. fontSize 단위가 px인 건 의도하신 걸까요?

2024-12-05 13:04 UTC, llqqssttyy commented on app/component/Image/index.tsx
> +  return props.isError ? <S.Image {...props} alt="props" /> : null;
Image에서 에러 상태를 검사한다면 한 단계 더 나아가서 error가 발생했을 때 Fallback Image를 보여주는 게 사용자 경험에 좋을 것 같아요.
러기는 어떻게 생각하시나요?

2024-12-05 13:04 UTC, llqqssttyy commented on app/component/Image/style.ts
> +});
👍

2024-12-05 13:04 UTC, llqqssttyy commented on app/component/LogPreview/index.tsx
> +  imageUrl: string;
imageUrl이 없는 경우를 대비해서 optional하게 받아야 할 것 같아요~

2024-12-06 00:31 UTC, lurgi commented on src/stitches.ts
> +});
우선 스타일 사용에 있어서 기본적으로 사용하는 px을 사용했어요! rem사용은 추후에 논의해보아용

2024-12-06 00:36 UTC, lurgi commented on app/component/Image/index.tsx
> +  return props.isError ? <S.Image {...props} alt="props" /> : null;
해당 부분은 showFallback이란 prop을 만들어서 보여주는 방식도 괜찮을 거란 생각이 드네요!
fallback 이미지에 대한 디자인이나 레퍼런스가 있으실까용?!

2024-12-06 00:36 UTC, lurgi commented on app/component/LogPreview/index.tsx
> +  imageUrl: string;
꼼꼼쓰👍

2024-12-06 02:14 UTC, lurgi commented on app/component/Image/index.tsx
> +  return props.isError ? <S.Image {...props} alt="props" /> : null;
<img width="249" alt="image" src="https://github.com/user-attachments/assets/d5e7dd97-7828-4250-a8bc-c3d74f926293">
일단 해당 이미지로 작업 시작하겠습니당!

2024-12-06 05:45 UTC, llqqssttyy approved these changes, later dismissed
리뷰드린 내용 모두 반영해주셔서 감사합니다 _럴기_ 🙇‍♀️
이미지 컴포넌트의 가독성을 향상시킬 아이디어를 남겼는데
나중에 상태가 복잡해질 때 개선해도 상관 없어서 apporve 드립니다~ 고생하셨어용!

2024-12-06 05:45 UTC, llqqssttyy commented on app/component/Image/index.tsx
> +}
지금도 괜찮지만 나중에 로딩 상태가 추가될 걸 고려해서 early return으로 작성하는 건 어떨까요~?

```jsx
export default function Image({ isError, src, ...props }: ImageProps) {
  if (isError) {
    return <BiSolidError size={'50%'} />;
  }
  return src ? <S.Image {...props} /> : null;
}
```

2024-12-06 06:23 UTC, lurgi commented on app/component/Image/index.tsx
> +}
훨씬 가독성 있다고 생각되어서 반영합니다!

2024-12-06 06:27 UTC, llqqssttyy approved these changes
src 넘기는 걸 깜빡했는데 고쳐주셨네용 감사합니다~~ 머지하시죵

2024-12-06 06:36 UTC, merged